"use client";

import { useState } from "react";

import { AgentFlow } from "@/components/agent-flow";
import type { TraceEntry } from "@/hooks/use-chat";
import { describeStage } from "@/lib/chat";

/**
 * What Ray actually did, per turn.
 *
 * Every line is recorded by the code that performed the step — never generated by
 * the model, which would produce a convincing fiction instead of a fact
 * (docs/12). Collapsed by default: transparency should be available, not loud.
 */
export function AgentTrace({
  trace,
  agentName,
  durationMs,
}: {
  trace: TraceEntry[];
  agentName?: string;
  durationMs?: number;
}) {
  const [open, setOpen] = useState(false);
  if (trace.length === 0) return null;

  const degraded = trace.some((entry) => entry.detail.degraded_from !== undefined);

  return (
    <div className="mt-2">
      <button
        type="button"
        onClick={() => setOpen(!open)}
        aria-expanded={open}
        className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-hud-muted transition-colors hover:text-hud-accent"
      >
        <span className={`transition-transform ${open ? "rotate-90" : ""}`}>▸</span>
        {agentName ?? "trace"}
        {durationMs !== undefined && <span>· {durationMs}ms</span>}
        <span>· {trace.length} steps</span>
        {degraded && <span className="text-hud-warn">· fallback</span>}
      </button>

      {open && (
        <>
          <AgentFlow trace={trace} durationMs={durationMs} />
          <ol className="mt-3 space-y-1 border-l border-hud-border pl-3">
            {trace.map((entry, index) => (
              <li
                key={`${entry.stage}-${index}`}
                className="flex items-baseline gap-2 font-mono text-[11px] text-hud-muted"
              >
                <span className="w-16 shrink-0 uppercase tracking-widest text-hud-accent/70">
                  {entry.stage}
                </span>
                <span>{describeStage(entry.stage, entry.detail)}</span>
              </li>
            ))}
          </ol>
        </>
      )}
    </div>
  );
}
